name: Build PR

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build
        run: docker build
