on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

name: Check image updates

jobs:
  update:
    name: Check image updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      changes_detected: ${{ steps.check-for-updates.outputs.changes_detected }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.3.0

      - name: Check for updates
        id: check-for-updates
        run:  "${GITHUB_WORKSPACE}/.github/updateDockerfile.sh"

      - name: Build Docker Image
        if: steps.check-for-updates.outputs.changes_detected == 'true'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: shanemcc/docker-omsa
          tags: dev-latest
          dockerfile: Dockerfile
          registry: docker.io
          pushImage: false

      - name: Push changed file
        if: steps.check-for-updates.outputs.changes_detected == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update Dockerfile (${{ steps.check-for-updates.outputs.changed_items }})
            file_pattern: 'Dockerfile'

  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    needs: update
    if: needs.update.outputs.changes_detected == 'true'
